kind: pipeline
name: build

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init --recursive

- name: build
  image: microsoft/dotnet:2-sdk
  commands:
    - dotnet publish --configuration release --output /release Jellyfin.Server

- name: clone-dotnet-compat
  image: docker:git
  commands:
    - git clone --depth 1 https://github.com/EraYaN/dotnet-compatibility
  when:
    event:
    - pull_request

- name: build-dotnet-compat
  image: microsoft/dotnet:2-sdk
  commands:
    - dotnet publish --configuration release --output /tools dotnet-compatibility/CompatibilityCheckerCoreCLI
  when:
    event:
    - pull_request

- name: download-last-nuget-release-common
  image: plugins/download
  settings:
    source: https://www.nuget.org/api/v2/package/Jellyfin.Common
    destination: Jellyfin.Common.nupkg
  when:
    event:
    - pull_request

- name: download-last-nuget-release-model
  image: plugins/download
  settings:
    source: https://www.nuget.org/api/v2/package/Jellyfin.Model
    destination: Jellyfin.Model.nupkg
  when:
    event:
    - pull_request

- name: download-last-nuget-release-controller
  image: plugins/download
  settings:
    source: https://www.nuget.org/api/v2/package/Jellyfin.Controller
    destination: Jellyfin.Controller.nupkg
  when:
    event:
    - pull_request

- name: download-last-nuget-release-naming
  image: plugins/download
  settings:
    source: https://www.nuget.org/api/v2/package/Jellyfin.Naming
    destination: Jellyfin.Naming.nupkg
  when:
    event:
    - pull_request

- name: extract-downloaded-nuget-packages
  image: garthk/unzip
  commands:
  - unzip -j Jellyfin.Common.nupkg  "*.dll" -d /current-release
  - unzip -j Jellyfin.Model.nupkg  "*.dll" -d /current-release
  - unzip -j Jellyfin.Controller.nupkg  "*.dll" -d /current-release
  - unzip -j Jellyfin.Naming.nupkg  "*.dll" -d /current-release
  when:
    event:
    - pull_request

- name: run-dotnet-compat-common
  image: microsoft/dotnet:2-runtime
  err_ignore: true
  commands:
  - dotnet /tools/CompatibilityCheckerCoreCLI.dll /current-release/Jellyfin.Common.dll /release/Jellyfin.Common.dll
  when:
    event:
    - pull_request

- name: run-dotnet-compat-model
  image: microsoft/dotnet:2-runtime
  err_ignore: true
  commands:
  - dotnet /tools/CompatibilityCheckerCoreCLI.dll /current-release/Jellyfin.Model.dll /release/Jellyfin.Model.dll
  when:
    event:
    - pull_request

- name: run-dotnet-compat-controller
  image: microsoft/dotnet:2-runtime
  err_ignore: true
  commands:
  - dotnet /tools/CompatibilityCheckerCoreCLI.dll /current-release/Jellyfin.Controller.dll /release/Jellyfin.Controller.dll
  when:
    event:
    - pull_request

- name: run-dotnet-compat-naming
  image: microsoft/dotnet:2-runtime
  err_ignore: true
  commands:
  - dotnet /tools/CompatibilityCheckerCoreCLI.dll /current-release/Jellyfin.Naming.dll /release/Jellyfin.Naming.dll
  when:
    event:
    - pull_request
