pr:
  autoCancel: true

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-16.04

variables:
  - name: TestProjects
    value: ''
  - name: RestoreBuildProjects
    value: 'Jellyfin.Server/Jellyfin.Server.csproj'

#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971

jobs:
- job: Build
  steps:
  - checkout: self
    clean: false
    submodules: true
    persistCredentials: false

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(RestoreBuildProjects)'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '$(RestoreBuildProjects)'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '$(RestoreBuildProjects)'
      arguments: '--configuration $(BuildConfiguration)'
    enabled: false

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '$(RestoreBuildProjects)'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      artifactName: 'build-$(BuildConfiguration)'
      zipAfterPublish: false




